version: "3.8"


services:
  minecraft:
    image: itzg/minecraft-server

    container_name: minecraft

    ports:
      - "25565:25565"

    environment:
      TYPE: PAPER
      EULA: "TRUE"
      VERSION: 1.21.8
      MEMORYSIZE: "1G"

      REMOVE_OLD_MODS: true
      REMOVE_OLD_MODS_INCLUDE: "*.jar"

      PLUGINS: |
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.2/PAPER/ViaVersion-5.4.2.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.21.1/EssentialsX-2.21.1.jar
        https://download.luckperms.net/1595/fabric/LuckPerms-Fabric-5.5.10.jar
        https://cdn.modrinth.com/data/16vhQOQN/versions/SHT4Xj7n/minimotd-bukkit-2.1.7.jar
        https://github.com/Norbit4/TreeCuter/releases/download/v1.9.1/TreeCuter-v1.9.1.jar

    stdin_open: true
    tty: true

    deploy:
      resources:
        limits:
          memory: 1G

    volumes:
      - ./data:/data:rw

