version: "3.8"


services:
  minecraft:
    build:
      target: server

    container_name: minecraft

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    environment:
      PAPER_VERSION: 1.21.1
      PAPER_BUILD: 33
      EULA: "TRUE"
      MEMORYSIZE: "1G"

    stdin_open: true
    tty: true

    deploy:
      resources:
        limits:
          memory: 1G

    volumes:
      - ./data:/data:rw

